// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import {
  UpdateUserRequest,
  updateUserRequest,
  updateUserRequestRequest,
  updateUserRequestResponse,
} from '../../common/update-user-request';

/**
 * The shape of the model inside the application code - what the users use
 */
export const updateCsmRequest = z.lazy(() => {
  return z.object({
    user: updateUserRequest.optional(),
    displayImageUrl: z.string().optional(),
    meetingUrl: z.string().optional(),
  });
});

/**
 *
 * @typedef  {UpdateCsmRequest} updateCsmRequest
 * @property {UpdateUserRequest}
 * @property {string}
 * @property {string}
 */
export type UpdateCsmRequest = z.infer<typeof updateCsmRequest>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const updateCsmRequestResponse = z.lazy(() => {
  return z
    .object({
      user: updateUserRequestResponse.optional(),
      displayImageUrl: z.string().optional(),
      meetingUrl: z.string().optional(),
    })
    .transform((data) => ({
      user: data['user'],
      displayImageUrl: data['displayImageUrl'],
      meetingUrl: data['meetingUrl'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const updateCsmRequestRequest = z.lazy(() => {
  return z
    .object({
      user: updateUserRequestRequest.optional(),
      displayImageUrl: z.string().optional(),
      meetingUrl: z.string().optional(),
    })
    .transform((data) => ({
      user: data['user'],
      displayImageUrl: data['displayImageUrl'],
      meetingUrl: data['meetingUrl'],
    }));
});
