// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const createChecklistRequest = z.lazy(() => {
  return z.object({
    type: z.string(),
    clientId: z.string().optional(),
    opportunityId: z.string().optional(),
    eventId: z.string().optional(),
    label: z.string(),
    description: z.string(),
    key: z.string(),
    format: z.string().optional(),
    section: z.string().optional(),
    widgetType: z.string().optional(),
  });
});

/**
 *
 * @typedef  {CreateChecklistRequest} createChecklistRequest
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 */
export type CreateChecklistRequest = z.infer<typeof createChecklistRequest>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const createChecklistRequestResponse = z.lazy(() => {
  return z
    .object({
      type: z.string(),
      clientId: z.string().optional(),
      opportunityId: z.string().optional(),
      eventId: z.string().optional(),
      label: z.string(),
      description: z.string(),
      key: z.string(),
      format: z.string().optional(),
      section: z.string().optional(),
      widgetType: z.string().optional(),
    })
    .transform((data) => ({
      type: data['type'],
      clientId: data['clientId'],
      opportunityId: data['opportunityId'],
      eventId: data['eventId'],
      label: data['label'],
      description: data['description'],
      key: data['key'],
      format: data['format'],
      section: data['section'],
      widgetType: data['widgetType'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const createChecklistRequestRequest = z.lazy(() => {
  return z
    .object({
      type: z.string(),
      clientId: z.string().optional(),
      opportunityId: z.string().optional(),
      eventId: z.string().optional(),
      label: z.string(),
      description: z.string(),
      key: z.string(),
      format: z.string().optional(),
      section: z.string().optional(),
      widgetType: z.string().optional(),
    })
    .transform((data) => ({
      type: data['type'],
      clientId: data['clientId'],
      opportunityId: data['opportunityId'],
      eventId: data['eventId'],
      label: data['label'],
      description: data['description'],
      key: data['key'],
      format: data['format'],
      section: data['section'],
      widgetType: data['widgetType'],
    }));
});
