// This file was generated by liblab | https://liblab.com/

export interface PartnerControllerListParams {
  q?: string;
  languages?: string[];
  isBenevity?: string;
  impactLocation?: string[];
  focusArea?: string[];
  cityId?: string[];
  country?: string[];
}
