// This file was generated by liblab | https://liblab.com/

export type { UpdateFaqRequest } from './update-faq-request';
export type { CreateFaqRequest } from './create-faq-request';
export type { CreateDefaultFaqRequest } from './create-default-faq-request';
export type { CreateFaqVariantRequest } from './create-faq-variant-request';
