// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const apiVersion = z.union([z.literal('V1'), z.literal('V2')]);

export type ApiVersion = z.infer<typeof apiVersion>;
