// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const createDefaultQuestionRequest = z.lazy(() => {
  return z.object({
    type: z.string(),
    eventLocation: z.string(),
    fieldName: z.string(),
    isRequired: z.boolean(),
    isDefault: z.any(),
    canBeHidden: z.any(),
    hidden: z.any(),
    validationMetadata: z.any().optional(),
    variants: z.array(z.string()),
  });
});

/**
 *
 * @typedef  {CreateDefaultQuestionRequest} createDefaultQuestionRequest
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {boolean}
 * @property {any}
 * @property {any}
 * @property {any}
 * @property {any}
 * @property {string[]}
 */
export type CreateDefaultQuestionRequest = z.infer<typeof createDefaultQuestionRequest>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const createDefaultQuestionRequestResponse = z.lazy(() => {
  return z
    .object({
      type: z.string(),
      eventLocation: z.string(),
      fieldName: z.string(),
      isRequired: z.boolean(),
      isDefault: z.any(),
      canBeHidden: z.any(),
      hidden: z.any(),
      validationMetadata: z.any().optional(),
      variants: z.array(z.string()),
    })
    .transform((data) => ({
      type: data['type'],
      eventLocation: data['eventLocation'],
      fieldName: data['fieldName'],
      isRequired: data['isRequired'],
      isDefault: data['isDefault'],
      canBeHidden: data['canBeHidden'],
      hidden: data['hidden'],
      validationMetadata: data['validationMetadata'],
      variants: data['variants'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const createDefaultQuestionRequestRequest = z.lazy(() => {
  return z
    .object({
      type: z.string(),
      eventLocation: z.string(),
      fieldName: z.string(),
      isRequired: z.boolean(),
      isDefault: z.any(),
      canBeHidden: z.any(),
      hidden: z.any(),
      validationMetadata: z.any().optional(),
      variants: z.array(z.string()),
    })
    .transform((data) => ({
      type: data['type'],
      eventLocation: data['eventLocation'],
      fieldName: data['fieldName'],
      isRequired: data['isRequired'],
      isDefault: data['isDefault'],
      canBeHidden: data['canBeHidden'],
      hidden: data['hidden'],
      validationMetadata: data['validationMetadata'],
      variants: data['variants'],
    }));
});
