// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const createPartnerCorporateAddressRequest = z.lazy(() => {
  return z.object({
    line1: z.string(),
    recipientName: z.string(),
    email: z.string(),
    phoneNumber: z.string(),
    isdCode: z.string().optional(),
    title: z.string(),
    latitude: z.string(),
    longitude: z.string(),
    city: z.string(),
    province: z.string(),
    postalCode: z.string(),
    country: z.string(),
    url: z.string(),
    metadata: z.any(),
  });
});

/**
 *
 * @typedef  {CreatePartnerCorporateAddressRequest} createPartnerCorporateAddressRequest
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {any}
 */
export type CreatePartnerCorporateAddressRequest = z.infer<typeof createPartnerCorporateAddressRequest>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const createPartnerCorporateAddressRequestResponse = z.lazy(() => {
  return z
    .object({
      line1: z.string(),
      recipientName: z.string(),
      email: z.string(),
      phoneNumber: z.string(),
      isdCode: z.string().optional(),
      title: z.string(),
      latitude: z.string(),
      longitude: z.string(),
      city: z.string(),
      province: z.string(),
      postalCode: z.string(),
      country: z.string(),
      url: z.string(),
      metadata: z.any(),
    })
    .transform((data) => ({
      line1: data['line1'],
      recipientName: data['recipientName'],
      email: data['email'],
      phoneNumber: data['phoneNumber'],
      isdCode: data['isdCode'],
      title: data['title'],
      latitude: data['latitude'],
      longitude: data['longitude'],
      city: data['city'],
      province: data['province'],
      postalCode: data['postalCode'],
      country: data['country'],
      url: data['url'],
      metadata: data['metadata'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const createPartnerCorporateAddressRequestRequest = z.lazy(() => {
  return z
    .object({
      line1: z.string(),
      recipientName: z.string(),
      email: z.string(),
      phoneNumber: z.string(),
      isdCode: z.string().optional(),
      title: z.string(),
      latitude: z.string(),
      longitude: z.string(),
      city: z.string(),
      province: z.string(),
      postalCode: z.string(),
      country: z.string(),
      url: z.string(),
      metadata: z.any(),
    })
    .transform((data) => ({
      line1: data['line1'],
      recipientName: data['recipientName'],
      email: data['email'],
      phoneNumber: data['phoneNumber'],
      isdCode: data['isdCode'],
      title: data['title'],
      latitude: data['latitude'],
      longitude: data['longitude'],
      city: data['city'],
      province: data['province'],
      postalCode: data['postalCode'],
      country: data['country'],
      url: data['url'],
      metadata: data['metadata'],
    }));
});
