// This file was generated by liblab | https://liblab.com/

export type { CreatePartnerRequest } from './create-partner-request';
export type { CreatePartnerCorporateAddressRequest } from './create-partner-corporate-address-request';
export type { CreatePartnerShippingAddress } from './create-partner-shipping-address';
export type { DisablePartnerRequest } from './disable-partner-request';
export type { UpdatePartnerRequest } from './update-partner-request';
export type { UpdatePartnerCorporateAddressRequest } from './update-partner-corporate-address-request';
