// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const createBulkJobRequest = z.lazy(() => {
  return z.object({
    type: z.string(),
    payload: z.any(),
  });
});

/**
 *
 * @typedef  {CreateBulkJobRequest} createBulkJobRequest
 * @property {string}
 * @property {any}
 */
export type CreateBulkJobRequest = z.infer<typeof createBulkJobRequest>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const createBulkJobRequestResponse = z.lazy(() => {
  return z
    .object({
      type: z.string(),
      payload: z.any(),
    })
    .transform((data) => ({
      type: data['type'],
      payload: data['payload'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const createBulkJobRequestRequest = z.lazy(() => {
  return z
    .object({
      type: z.string(),
      payload: z.any(),
    })
    .transform((data) => ({
      type: data['type'],
      payload: data['payload'],
    }));
});
