// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const createShipmentRequestDispatchType = z.union([z.literal('pickup'), z.literal('drop')]);

export type CreateShipmentRequestDispatchType = z.infer<typeof createShipmentRequestDispatchType>;
