// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const status = z.union([
  z.literal('not_fulfilled'),
  z.literal('fulfilled'),
  z.literal('ready_to_dispatch'),
  z.literal('dispatched'),
  z.literal('delivered'),
]);

export type Status = z.infer<typeof status>;
