// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const updateShipmentRequestDispatchType = z.union([z.literal('pickup'), z.literal('drop')]);

export type UpdateShipmentRequestDispatchType = z.infer<typeof updateShipmentRequestDispatchType>;
