// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const updateShipmentRequestCarrier = z.union([
  z.literal('fedex'),
  z.literal('ups'),
  z.literal('amazon'),
  z.literal('dhl'),
  z.literal('dtdc'),
  z.literal('delhivery'),
  z.literal('others'),
  z.literal('host'),
]);

export type UpdateShipmentRequestCarrier = z.infer<typeof updateShipmentRequestCarrier>;
