// This file was generated by liblab | https://liblab.com/

export interface AgentCatalogueControllerListParams {
  partnerLanguages?: string[];
  isBenevity?: boolean;
  partnerImpactLocation?: string[];
  partnerFocusArea?: string[];
  partnerCity?: string[];
  partnerCountryId?: string[];
}
