// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const createPartnerPocRequest = z.lazy(() => {
  return z.object({
    partnerId: z.string(),
    firstName: z.string(),
    lastName: z.string(),
    phoneNumber: z.string(),
    isdCode: z.string(),
    email: z.string(),
  });
});

/**
 *
 * @typedef  {CreatePartnerPocRequest} createPartnerPocRequest
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 */
export type CreatePartnerPocRequest = z.infer<typeof createPartnerPocRequest>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const createPartnerPocRequestResponse = z.lazy(() => {
  return z
    .object({
      partnerId: z.string(),
      firstName: z.string(),
      lastName: z.string(),
      phoneNumber: z.string(),
      isdCode: z.string(),
      email: z.string(),
    })
    .transform((data) => ({
      partnerId: data['partnerId'],
      firstName: data['firstName'],
      lastName: data['lastName'],
      phoneNumber: data['phoneNumber'],
      isdCode: data['isdCode'],
      email: data['email'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const createPartnerPocRequestRequest = z.lazy(() => {
  return z
    .object({
      partnerId: z.string(),
      firstName: z.string(),
      lastName: z.string(),
      phoneNumber: z.string(),
      isdCode: z.string(),
      email: z.string(),
    })
    .transform((data) => ({
      partnerId: data['partnerId'],
      firstName: data['firstName'],
      lastName: data['lastName'],
      phoneNumber: data['phoneNumber'],
      isdCode: data['isdCode'],
      email: data['email'],
    }));
});
