// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const disableHostRequest = z.lazy(() => {
  return z.object({
    disable: z.boolean(),
  });
});

/**
 *
 * @typedef  {DisableHostRequest} disableHostRequest
 * @property {boolean}
 */
export type DisableHostRequest = z.infer<typeof disableHostRequest>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const disableHostRequestResponse = z.lazy(() => {
  return z
    .object({
      disable: z.boolean(),
    })
    .transform((data) => ({
      disable: data['disable'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const disableHostRequestRequest = z.lazy(() => {
  return z
    .object({
      disable: z.boolean(),
    })
    .transform((data) => ({
      disable: data['disable'],
    }));
});
