// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const source = z.union([z.literal('GOODEAR'), z.literal('HOST_APP'), z.literal('MANUAL')]);

export type Source = z.infer<typeof source>;
