// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const updateEventChampionRequestRole = z.union([
  z.literal('VOLUNTEER'),
  z.literal('CHAMPION'),
  z.literal('POC'),
]);

export type UpdateEventChampionRequestRole = z.infer<typeof updateEventChampionRequestRole>;
