// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const createCvpTokenRequest = z.lazy(() => {
  return z.object({
    clientVolunteeringPlatformId: z.string(),
  });
});

/**
 *
 * @typedef  {CreateCvpTokenRequest} createCvpTokenRequest
 * @property {string}
 */
export type CreateCvpTokenRequest = z.infer<typeof createCvpTokenRequest>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const createCvpTokenRequestResponse = z.lazy(() => {
  return z
    .object({
      clientVolunteeringPlatformId: z.string(),
    })
    .transform((data) => ({
      clientVolunteeringPlatformId: data['clientVolunteeringPlatformId'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const createCvpTokenRequestRequest = z.lazy(() => {
  return z
    .object({
      clientVolunteeringPlatformId: z.string(),
    })
    .transform((data) => ({
      clientVolunteeringPlatformId: data['clientVolunteeringPlatformId'],
    }));
});
