// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const bulkCreateGoodfieRequest = z.lazy(() => {
  return z.object({
    urls: z.array(z.string()),
    source: z.string(),
    showOnEventPage: z.boolean().optional(),
  });
});

/**
 *
 * @typedef  {BulkCreateGoodfieRequest} bulkCreateGoodfieRequest
 * @property {string[]}
 * @property {string}
 * @property {boolean}
 */
export type BulkCreateGoodfieRequest = z.infer<typeof bulkCreateGoodfieRequest>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const bulkCreateGoodfieRequestResponse = z.lazy(() => {
  return z
    .object({
      urls: z.array(z.string()),
      source: z.string(),
      showOnEventPage: z.boolean().optional(),
    })
    .transform((data) => ({
      urls: data['urls'],
      source: data['source'],
      showOnEventPage: data['showOnEventPage'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const bulkCreateGoodfieRequestRequest = z.lazy(() => {
  return z
    .object({
      urls: z.array(z.string()),
      source: z.string(),
      showOnEventPage: z.boolean().optional(),
    })
    .transform((data) => ({
      urls: data['urls'],
      source: data['source'],
      showOnEventPage: data['showOnEventPage'],
    }));
});
