// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const createGoodfieRequest = z.lazy(() => {
  return z.object({
    url: z.string(),
    source: z.string(),
    eventId: z.string(),
    showOnEventPage: z.boolean().optional(),
  });
});

/**
 *
 * @typedef  {CreateGoodfieRequest} createGoodfieRequest
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {boolean}
 */
export type CreateGoodfieRequest = z.infer<typeof createGoodfieRequest>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const createGoodfieRequestResponse = z.lazy(() => {
  return z
    .object({
      url: z.string(),
      source: z.string(),
      eventId: z.string(),
      showOnEventPage: z.boolean().optional(),
    })
    .transform((data) => ({
      url: data['url'],
      source: data['source'],
      eventId: data['eventId'],
      showOnEventPage: data['showOnEventPage'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const createGoodfieRequestRequest = z.lazy(() => {
  return z
    .object({
      url: z.string(),
      source: z.string(),
      eventId: z.string(),
      showOnEventPage: z.boolean().optional(),
    })
    .transform((data) => ({
      url: data['url'],
      source: data['source'],
      eventId: data['eventId'],
      showOnEventPage: data['showOnEventPage'],
    }));
});
