// This file was generated by liblab | https://liblab.com/

export type { UpdateGoodfieRequest } from './update-goodfie-request';
export type { CreateGoodfieRequest } from './create-goodfie-request';
export type { BulkCreateGoodfieRequest } from './bulk-create-goodfie-request';
