// This file was generated by liblab | https://liblab.com/

export type { CreateTestimonialRequest } from './create-testimonial-request';
export type { UpdateTestimonialRequest } from './update-testimonial-request';
