// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const updateTestimonialRequest = z.lazy(() => {
  return z.object({
    hidden: z.boolean().optional(),
    embedLink: z.string().optional(),
    postLink: z.string().optional(),
  });
});

/**
 *
 * @typedef  {UpdateTestimonialRequest} updateTestimonialRequest
 * @property {boolean}
 * @property {string}
 * @property {string}
 */
export type UpdateTestimonialRequest = z.infer<typeof updateTestimonialRequest>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const updateTestimonialRequestResponse = z.lazy(() => {
  return z
    .object({
      hidden: z.boolean().optional(),
      embedLink: z.string().optional(),
      postLink: z.string().optional(),
    })
    .transform((data) => ({
      hidden: data['hidden'],
      embedLink: data['embedLink'],
      postLink: data['postLink'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const updateTestimonialRequestRequest = z.lazy(() => {
  return z
    .object({
      hidden: z.boolean().optional(),
      embedLink: z.string().optional(),
      postLink: z.string().optional(),
    })
    .transform((data) => ({
      hidden: data['hidden'],
      embedLink: data['embedLink'],
      postLink: data['postLink'],
    }));
});
