// This file was generated by liblab | https://liblab.com/

export type { CreateChampionsConfigRequest } from './create-champions-config-request';
export type { UpdateChampionsConfigRequest } from './update-champions-config-request';
