// This file was generated by liblab | https://liblab.com/

export interface ActivityPartnerControllerListParams {
  partnerLanguages?: string[];
  isBenevity?: boolean;
  partnerImpactLocation?: string[];
  partnerFocusArea?: string[];
  partnerCity?: string[];
  partnerCountryId?: string[];
}
