// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const updateEventContextRequest = z.lazy(() => {
  return z.object({
    context: z.string(),
  });
});

/**
 *
 * @typedef  {UpdateEventContextRequest} updateEventContextRequest
 * @property {string}
 */
export type UpdateEventContextRequest = z.infer<typeof updateEventContextRequest>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const updateEventContextRequestResponse = z.lazy(() => {
  return z
    .object({
      context: z.string(),
    })
    .transform((data) => ({
      context: data['context'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const updateEventContextRequestRequest = z.lazy(() => {
  return z
    .object({
      context: z.string(),
    })
    .transform((data) => ({
      context: data['context'],
    }));
});
