// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const createUserRequest = z.lazy(() => {
  return z.object({
    email: z.string(),
    firstName: z.string(),
    lastName: z.string(),
    profileImageUrl: z.string().optional(),
    team: z.string(),
    meetingUrl: z.string().optional(),
  });
});

/**
 *
 * @typedef  {CreateUserRequest} createUserRequest
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 */
export type CreateUserRequest = z.infer<typeof createUserRequest>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const createUserRequestResponse = z.lazy(() => {
  return z
    .object({
      email: z.string(),
      firstName: z.string(),
      lastName: z.string(),
      profileImageUrl: z.string().optional(),
      team: z.string(),
      meetingUrl: z.string().optional(),
    })
    .transform((data) => ({
      email: data['email'],
      firstName: data['firstName'],
      lastName: data['lastName'],
      profileImageUrl: data['profileImageUrl'],
      team: data['team'],
      meetingUrl: data['meetingUrl'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const createUserRequestRequest = z.lazy(() => {
  return z
    .object({
      email: z.string(),
      firstName: z.string(),
      lastName: z.string(),
      profileImageUrl: z.string().optional(),
      team: z.string(),
      meetingUrl: z.string().optional(),
    })
    .transform((data) => ({
      email: data['email'],
      firstName: data['firstName'],
      lastName: data['lastName'],
      profileImageUrl: data['profileImageUrl'],
      team: data['team'],
      meetingUrl: data['meetingUrl'],
    }));
});
