// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const createShipmentAddress = z.lazy(() => {
  return z.object({
    line1: z.string(),
    line2: z.string().optional(),
    latitude: z.string().optional(),
    longitude: z.string().optional(),
    city: z.string(),
    province: z.string().optional(),
    postalCode: z.string().optional(),
    country: z.string(),
    url: z.string().optional(),
    metadata: z.any().optional(),
    email: z.string(),
    isdCode: z.string(),
    phoneNumber: z.string(),
    recipientName: z.string(),
  });
});

/**
 *
 * @typedef  {CreateShipmentAddress} createShipmentAddress
 * @property {string} - Address line 1
 * @property {string} - Address line 2
 * @property {string} - Latitude of the address
 * @property {string} - Longitude of the address
 * @property {string} - City of the address
 * @property {string} - Province of the address
 * @property {string} - Postal code of the address
 * @property {string} - Country of the address
 * @property {string} - URL associated with the address
 * @property {any} - Metadata associated with the address
 * @property {string} - Email associated with the address
 * @property {string} - ISD code for the phone number
 * @property {string} - Phone number
 * @property {string} - Name of the recipient
 */
export type CreateShipmentAddress = z.infer<typeof createShipmentAddress>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const createShipmentAddressResponse = z.lazy(() => {
  return z
    .object({
      line1: z.string(),
      line2: z.string().optional(),
      latitude: z.string().optional(),
      longitude: z.string().optional(),
      city: z.string(),
      province: z.string().optional(),
      postalCode: z.string().optional(),
      country: z.string(),
      url: z.string().optional(),
      metadata: z.any().optional(),
      email: z.string(),
      isdCode: z.string(),
      phoneNumber: z.string(),
      recipientName: z.string(),
    })
    .transform((data) => ({
      line1: data['line1'],
      line2: data['line2'],
      latitude: data['latitude'],
      longitude: data['longitude'],
      city: data['city'],
      province: data['province'],
      postalCode: data['postalCode'],
      country: data['country'],
      url: data['url'],
      metadata: data['metadata'],
      email: data['email'],
      isdCode: data['isdCode'],
      phoneNumber: data['phoneNumber'],
      recipientName: data['recipientName'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const createShipmentAddressRequest = z.lazy(() => {
  return z
    .object({
      line1: z.string(),
      line2: z.string().optional(),
      latitude: z.string().optional(),
      longitude: z.string().optional(),
      city: z.string(),
      province: z.string().optional(),
      postalCode: z.string().optional(),
      country: z.string(),
      url: z.string().optional(),
      metadata: z.any().optional(),
      email: z.string(),
      isdCode: z.string(),
      phoneNumber: z.string(),
      recipientName: z.string(),
    })
    .transform((data) => ({
      line1: data['line1'],
      line2: data['line2'],
      latitude: data['latitude'],
      longitude: data['longitude'],
      city: data['city'],
      province: data['province'],
      postalCode: data['postalCode'],
      country: data['country'],
      url: data['url'],
      metadata: data['metadata'],
      email: data['email'],
      isdCode: data['isdCode'],
      phoneNumber: data['phoneNumber'],
      recipientName: data['recipientName'],
    }));
});
