// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const deleteFileRequest = z.lazy(() => {
  return z.object({
    key: z.string(),
    bucket: z.string().optional(),
    filePath: z.string().optional(),
  });
});

/**
 *
 * @typedef  {DeleteFileRequest} deleteFileRequest
 * @property {string}
 * @property {string}
 * @property {string}
 */
export type DeleteFileRequest = z.infer<typeof deleteFileRequest>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const deleteFileRequestResponse = z.lazy(() => {
  return z
    .object({
      key: z.string(),
      bucket: z.string().optional(),
      filePath: z.string().optional(),
    })
    .transform((data) => ({
      key: data['key'],
      bucket: data['bucket'],
      filePath: data['filePath'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const deleteFileRequestRequest = z.lazy(() => {
  return z
    .object({
      key: z.string(),
      bucket: z.string().optional(),
      filePath: z.string().optional(),
    })
    .transform((data) => ({
      key: data['key'],
      bucket: data['bucket'],
      filePath: data['filePath'],
    }));
});
