// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const updateUserRequest = z.lazy(() => {
  return z.object({
    firstName: z.string().optional(),
    lastName: z.string().optional(),
    team: z.string().optional(),
    profileImageUrl: z.string().optional(),
    meetingUrl: z.string().optional(),
  });
});

/**
 *
 * @typedef  {UpdateUserRequest} updateUserRequest
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 */
export type UpdateUserRequest = z.infer<typeof updateUserRequest>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const updateUserRequestResponse = z.lazy(() => {
  return z
    .object({
      firstName: z.string().optional(),
      lastName: z.string().optional(),
      team: z.string().optional(),
      profileImageUrl: z.string().optional(),
      meetingUrl: z.string().optional(),
    })
    .transform((data) => ({
      firstName: data['firstName'],
      lastName: data['lastName'],
      team: data['team'],
      profileImageUrl: data['profileImageUrl'],
      meetingUrl: data['meetingUrl'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const updateUserRequestRequest = z.lazy(() => {
  return z
    .object({
      firstName: z.string().optional(),
      lastName: z.string().optional(),
      team: z.string().optional(),
      profileImageUrl: z.string().optional(),
      meetingUrl: z.string().optional(),
    })
    .transform((data) => ({
      firstName: data['firstName'],
      lastName: data['lastName'],
      team: data['team'],
      profileImageUrl: data['profileImageUrl'],
      meetingUrl: data['meetingUrl'],
    }));
});
