// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const updateShipmentAddress = z.lazy(() => {
  return z.object({
    line1: z.string().optional(),
    line2: z.string().optional(),
    latitude: z.string().optional(),
    longitude: z.string().optional(),
    city: z.string().optional(),
    province: z.string().optional(),
    postalCode: z.string().optional(),
    country: z.string().optional(),
    url: z.string().optional(),
    metadata: z.any().optional(),
    email: z.string().optional(),
    isdCode: z.string().optional(),
    phoneNumber: z.string().optional(),
    recipientName: z.string().optional(),
  });
});

/**
 *
 * @typedef  {UpdateShipmentAddress} updateShipmentAddress
 * @property {string} - Address line 1
 * @property {string} - Address line 2
 * @property {string} - Latitude coordinate
 * @property {string} - Longitude coordinate
 * @property {string} - City
 * @property {string} - Province or state
 * @property {string} - Postal code
 * @property {string} - Country
 * @property {string} - URL associated with the address
 * @property {any} - Additional metadata related to the address
 * @property {string} - Email of the recipient or sender
 * @property {string} - ISD code (international dialing code)
 * @property {string} - Phone number of the recipient or sender
 * @property {string} - Name of the recipient or sender
 */
export type UpdateShipmentAddress = z.infer<typeof updateShipmentAddress>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const updateShipmentAddressResponse = z.lazy(() => {
  return z
    .object({
      line1: z.string().optional(),
      line2: z.string().optional(),
      latitude: z.string().optional(),
      longitude: z.string().optional(),
      city: z.string().optional(),
      province: z.string().optional(),
      postalCode: z.string().optional(),
      country: z.string().optional(),
      url: z.string().optional(),
      metadata: z.any().optional(),
      email: z.string().optional(),
      isdCode: z.string().optional(),
      phoneNumber: z.string().optional(),
      recipientName: z.string().optional(),
    })
    .transform((data) => ({
      line1: data['line1'],
      line2: data['line2'],
      latitude: data['latitude'],
      longitude: data['longitude'],
      city: data['city'],
      province: data['province'],
      postalCode: data['postalCode'],
      country: data['country'],
      url: data['url'],
      metadata: data['metadata'],
      email: data['email'],
      isdCode: data['isdCode'],
      phoneNumber: data['phoneNumber'],
      recipientName: data['recipientName'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const updateShipmentAddressRequest = z.lazy(() => {
  return z
    .object({
      line1: z.string().optional(),
      line2: z.string().optional(),
      latitude: z.string().optional(),
      longitude: z.string().optional(),
      city: z.string().optional(),
      province: z.string().optional(),
      postalCode: z.string().optional(),
      country: z.string().optional(),
      url: z.string().optional(),
      metadata: z.any().optional(),
      email: z.string().optional(),
      isdCode: z.string().optional(),
      phoneNumber: z.string().optional(),
      recipientName: z.string().optional(),
    })
    .transform((data) => ({
      line1: data['line1'],
      line2: data['line2'],
      latitude: data['latitude'],
      longitude: data['longitude'],
      city: data['city'],
      province: data['province'],
      postalCode: data['postalCode'],
      country: data['country'],
      url: data['url'],
      metadata: data['metadata'],
      email: data['email'],
      isdCode: data['isdCode'],
      phoneNumber: data['phoneNumber'],
      recipientName: data['recipientName'],
    }));
});
